version: '3.5'
services:
  nameserver:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/todoDev
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
networks:
  default:
    name: web_dev